-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: :local var = require(module)https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
